"""criacao da tabela de usuarios e suas FKs

Revision ID: d8ef0e5a966a
Revises: 
Create Date: 2026-05-12 21:31:53.693988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ef0e5a966a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_IMD_CREDENCIAL',
    sa.Column('id_credencial', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('dt_criacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_credencial'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('senha')
    )
    op.create_table('TB_IMD_PLANO_ASSINATURA',
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('nm_plano', sa.String(length=10), nullable=False),
    sa.Column('vl_plano', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ds_beneficios', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_plano')
    )
    op.create_table('TB_IMD_TIPO_SANGUINEO',
    sa.Column('id_tp_sanguineo', sa.Integer(), nullable=False),
    sa.Column('nm_tipo_sanguineo', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id_tp_sanguineo'),
    sa.UniqueConstraint('nm_tipo_sanguineo')
    )
    op.create_table('TB_IMD_USUARIO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_usuario', sa.String(length=80), nullable=False),
    sa.Column('dt_nascimento', sa.Date(), nullable=False),
    sa.Column('nr_cpf', sa.String(length=11), nullable=False),
    sa.Column('id_tp_sanguineo', sa.Integer(), nullable=False),
    sa.Column('id_credencial', sa.Integer(), nullable=False),
    sa.Column('id_plano_assinatura', sa.Integer(), nullable=False),
    sa.CheckConstraint('dt_nascimento <= GETDATE()', name='check_data_nascimento_valida'),
    sa.ForeignKeyConstraint(['id_credencial'], ['TB_IMD_CREDENCIAL.id_credencial'], ),
    sa.ForeignKeyConstraint(['id_plano_assinatura'], ['TB_IMD_PLANO_ASSINATURA.id_plano'], ),
    sa.ForeignKeyConstraint(['id_tp_sanguineo'], ['TB_IMD_TIPO_SANGUINEO.id_tp_sanguineo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nr_cpf')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_IMD_USUARIO')
    op.drop_table('TB_IMD_TIPO_SANGUINEO')
    op.drop_table('TB_IMD_PLANO_ASSINATURA')
    op.drop_table('TB_IMD_CREDENCIAL')
    # ### end Alembic commands ###
